### ISSUE TITLE
Simit compilation errors

### ISSUE THREAD

**Issue by luchesart** [simit-lang/simit#113]
Hi,
I am trying to build Simit in Google cloud in Linux, and after building everything, I have compilation issues

"/home/kostov_vm/simit.git/trunk/src/util/collections.h:67:72: error: ‘f’ was not declared in this scope
   std::transform(collection.begin(), collection.end(), result.begin(), f);
                                                                        ^
In file included from /home/kostov_vm/simit.git/trunk/src/stencils.h:10:0,
                 from /home/kostov_vm/simit.git/trunk/src/storage.h:9,
                 from /home/kostov_vm/simit.git/trunk/src/func.h:4,
                 from /home/kostov_vm/simit.git/trunk/src/ir.h:9,
                 from /home/kostov_vm/simit.git/trunk/src/environment.cpp:4:
/home/kostov_vm/simit.git/trunk/src/util/collections.h:64:35: error: ‘std::function’ has not been declared
                              std::function<ResultValue(ParamValue)> f) {
                                   ^~~~~~~~
/home/kostov_vm/simit.git/trunk/src/util/collections.h:64:43: error: expected ‘,’ or ‘...’ before ‘<’ token
                              std::function<ResultValue(ParamValue)> f) {
                                           ^
/home/kostov_vm/simit.git/trunk/src/util/collections.h: In function ‘std::vector<ResultValue> simit::util::map(cons
t Collection&, int)’:
/home/kostov_vm/simit.git/trunk/src/util/collections.h:67:72: error: ‘f’ was not declared in this scope
   std::transform(collection.begin(), collection.end(), result.begin(), f);
                                                                        ^
src/CMakeFiles/simit.dir/build.make:206: recipe for target 'src/CMakeFiles/simit.dir/graph.cpp.o' failed
make[2]: *** [src/CMakeFiles/simit.dir/graph.cpp.o] Error 1
src/CMakeFiles/simit.dir/build.make:62: recipe for target 'src/CMakeFiles/simit.dir/domain.cpp.o' failed
make[2]: *** [src/CMakeFiles/simit.dir/domain.cpp.o] Error 1
src/CMakeFiles/simit.dir/build.make:158: recipe for target 'src/CMakeFiles/simit.dir/func.cpp.o' failed
make[2]: *** [src/CMakeFiles/simit.dir/func.cpp.o] Error 1
src/CMakeFiles/simit.dir/build.make:134: recipe for target 'src/CMakeFiles/simit.dir/flatten.cpp.o' failed
make[2]: *** [src/CMakeFiles/simit.dir/flatten.cpp.o] Error 1
src/CMakeFiles/simit.dir/build.make:86: recipe for target 'src/CMakeFiles/simit.dir/environment.cpp.o' failed
make[2]: *** [src/CMakeFiles/simit.dir/environment.cpp.o] Error 1
CMakeFiles/Makefile2:96: recipe for target 'src/CMakeFiles/simit.dir/all' failed
make[1]: *** [src/CMakeFiles/simit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Linking CXX static library ../lib/libgtest.a
[  5%] Built target gtest
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
kostov_vm@glagol-1:~/simit.git/trunk/build$ "

I have built llvm3.7 and pointed it to Simit. Do I need to use specific C++ compilers to build Cmake 2.8.3 and then llvm3.7 in order to compile successfully Simit? I didn't find information here for such requirements

**Comment by stephenchouca** [comment]
It looks like a problem with missing headers. Can you try the latest commit and see if that solves the issue?

**Comment by luchesart** [comment]
Yes, thank you, that fixed the compilation error. I have other problem, but this issue is solved

**Comment by luchesart** [comment]
I want to ask what are the computational requirements for compiling Simit, how much RAM, how big swap area? My compilation blocks my computer repeatedly on 54 or 6% and exhausts the virtual memory
