### ISSUE TITLE
Add support for llvm > 3.4.2

### ISSUE THREAD

**Issue by fredrikbk** [simit-lang/simit#21]
We are currently bound to support llvm 3.4.2 because of the dependency on NVIDIA's NVCC library, which requires it. However, we should add support for later llvm versions, and over time transition away from NVCC.

**Comment by fredrikbk** [comment]
When we add the new version of LLVM we should try to get the auto-vectorizer to work on our linear algebra (to get some performance for free until we have our own linear algebra vectorizer). The rumors have it @CharithYMendis discovered that if you ask LLVM to unroll by 4 the auto-vectorizer starts working.

**Comment by piotroxp** [comment]
Absolute newb here I need this to work on LLVM3.8.1.1 on Archlinux asap. How do I get to it - apart from readmes and the code what are the core issue? regards

**Comment by fredrikbk** [comment]
@piotroxp  Are there any way you can use an older version of LLVM? The reason why we haven't left behind this version is the GPU backend, but there's a new pull request that I think fixes that. I will try to find some time to make LLVM 3.8.1.1 work tonight or later in the week if it is important for you, but I have other obligations so I can't promise anything.
