### ISSUE TITLE
cmake splits libaries path on "-"

### ISSUE THREAD

**Issue by symek** [simit-lang/simit#30]
Seems like custom llvm placed,say in:  "/opt/package/platform-linux/llvm/3.4.2/" isn't appreciated by simit CMake. 

It seems like some part of CMakeList.txt post process library path and splits it. Maybe here?

execute_process(COMMAND "${LLVM_CONFIG}" --libfiles ${LLVM_COMPONENTS} OUTPUT_VARIABLE LLVM_LIBS OUTPUT_STRIP_TRAILING_WHITESPACE)
separate_arguments(LLVM_LIBS)  # Turn the space-separate string into a ;-separated list
target_link_libraries(${PROJECT_NAME} PRIVATE ${LLVM_LIBS})

Not a terrible thing after all, but still might surprise someone.

**Comment by fredrikbk** [comment]
Custom llvm should work, but `llvm-config` does correctly handle spaces in the llvm path (see https://llvm.org/bugs/show_bug.cgi?id=27743). Is this the problem?

**Comment by symek** [comment]
Hi, sorry for not being precise! I compile simit on Centos7.1. When llvm-config is placed in:
$HOME/packages/llvm/3.4.2/platform-linux/arch-x86_64/bin/

it compiles, but throws an error on linking:

```
[ 57%] Linking CXX shared library ../lib/libsimit.so
/usr/bin/ld: cannot find -linux/arch-x86_64/lib

```
It clearly gets confused with _platform-linux_ section of the path returned by _llvm-config --libdir_. Running llvm-config from $HOME/llvm/bin works as expected. 

Thanks for your attention. I will try to make CMake working in such case.

**Comment by fredrikbk** [comment]
Ahh, it is probably confused by the combination `-l` as it is the lib include flag. I should be able to fix this shortly.

Thanks for the quick response!

**Comment by fredrikbk** [comment]
I believe this was fixed with 2b18597a7c3944322a1dc033dbf8f96e62a19758. It would be much appreciated if you can test the latest version on your system.

**Comment by symek** [comment]
Hi, 
thank you for fast response. It works like a charm now! 

A little glitch found by chance: there is a misleading typo in fem/spring building CMake file. It complains about missing SIMIT_LIB_DIR whereas it actually is expecting SIMIT_LIBRARY_DIR.

**Comment by fredrikbk** [comment]
Thanks for the help! I also fixed the cmake issue.
