### ISSUE TITLE
Just a question about the name of language

### ISSUE THREAD

**Issue by fatiherikli** [simit-lang/simit#4]
Why did you choose simit? Does it have a relationship with sesame rings? :)

**Comment by fredrikbk** [comment]
I'm afraid not, although I hear good things! Simit was more catchy than Sim
(as in simulation) and is also a play on the word Sim + MIT (where it's
mostly been developed).

**Comment by fatiherikli** [comment]
Thank you for the clarification :)

Maybe you notice that simits are sparse objects. I think you can use definition too :')

![simit matrix](https://s32.postimg.org/w22k1ok1x/simit.png)

**Comment by f** [comment]
https://en.wikipedia.org/wiki/Simit

**Comment by fredrikbk** [comment]
Good stuff to know!
