### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [simit-lang/simit#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [FieldData](https://github.com/simit-lang/simit/blob/7d2ea74012ca634d71e736150cdce33bafd51e29/src/graph.h#L445 "Destructor for FieldData")
* [IndexVarContent](https://github.com/simit-lang/simit/blob/7d2ea74012ca634d71e736150cdce33bafd51e29/src/indexvar.cpp#L8 "Destructor for IndexVarContent")
* [Set](https://github.com/simit-lang/simit/blob/7d2ea74012ca634d71e736150cdce33bafd51e29/src/graph.cpp#L10 "Destructor for Set")

**Comment by fredrikbk** [comment]
Thanks, good to know! Fixed in 1b21952. Happy to get issues and/or pull requests.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/simit-lang/simit/commit/1b21952cebae3bbc4ff26b7726a12c696606d150 "Deletion of a few unnecessary checks").
Is there [another update candidate left over](https://github.com/simit-lang/simit/blob/7d2ea74012ca634d71e736150cdce33bafd51e29/src/lower/lower_prints.cpp#L358 "Update candidate: LowerPrints::printIndices()")?
