### ISSUE TITLE
`new` and `delete` should be reserved

### ISSUE THREAD

**Issue by fredrikbk** [simit-lang/simit#52]
I think we should reserve the `new` and `delete` keyword in case we need them. Can we issue an error if someone tries to use them?

**Comment by fredrikbk** [comment]
@stephenchouca is this something you can easily add? Something like `Error: new is a reserved keyword` if someone tries to use it for a var, etc.

**Comment by stephenchouca** [comment]
This can be very easily checked as part of the parsing phase if we change the scanner to not treat `new` and `delete` as identifiers. The resulting error messages would be something more generic like `Error: expected an identifier but got 'new'` though. (This is actually a more general issue with errors found during the parsing phase; the corresponding error messages tend to be less specific and informative than those emitted during later phases. I can look into addressing this at some point in the future.)

**Comment by fredrikbk** [comment]
Yes, that solution works. We can improve the error messages over time.

**Comment by fredrikbk** [comment]
Fixed in ea529d0e5a3fd1bb7a39357be5cf9bb622d84536
